# Generated by Django 5.1.3 on 2024-11-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('service_by', models.CharField(max_length=255)),
                ('estimated_price', models.CharField(max_length=255)),
                ('estimated_date', models.DateField()),
                ('any_other_comments', models.CharField(max_length=255)),
            ],
        ),
    ]
