# Generated by Django 5.1.3 on 2024-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='estimation_document',
            field=models.FileField(default=True, upload_to='estimation/'),
        ),
        migrations.AddField(
            model_name='apply',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='item_name_or_number',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apply',
            name='photos_of_item',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/'),
        ),
        migrations.AddField(
            model_name='apply',
            name='reffered_by',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apply',
            name='work_type',
            field=models.CharField(choices=[('sale', 'sale'), ('service', 'service')], default=True, max_length=10),
        ),
    ]
