# Generated by Django 5.1.3 on 2024-11-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_alter_apply_estimation_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('u_address', models.TextField()),
                ('u_contact_number', models.CharField(max_length=10)),
                ('u_whatsapp_number', models.CharField(max_length=10)),
                ('u_reffered_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='custom_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
