# Generated by Django 5.1.3 on 2024-11-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_user_apply_custom_id'),
        ('workapp', '0004_user_remove_apply_address_remove_apply_name_and_more'),
    ]

    operations = [
    ]
