# Generated by Django 5.1.3 on 2024-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_merge_20241130_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='custom_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='u_contact_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
