# Generated by Django 5.1.3 on 2024-12-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_remove_apply_contact_number_remove_apply_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='reffered_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='whatsapp_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='any_other_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='service_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
