# Generated by Django 5.1.3 on 2024-12-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_apply_address_apply_contact_number_apply_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='estimated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='service_by',
            field=models.CharField(max_length=255),
        ),
    ]
