# Generated by Django 5.1.3 on 2024-12-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_alter_apply_estimated_date_alter_apply_service_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('technician_name', models.CharField(max_length=100)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('purpose', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FuelCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('purpose', models.TextField()),
                ('kilometers', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_photo', models.ImageField(upload_to='update/')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_bill_photo', models.ImageField(upload_to='update/')),
                ('vendor_eta', models.DateField()),
                ('vendor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
