# Generated by Django 5.1.3 on 2024-12-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0009_currentstatus_foodallowance_fuelcharge_itempurchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='whatsapp_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_whatsapp_number',
            field=models.CharField(max_length=15),
        ),
    ]
