# Generated by Django 5.1.3 on 2024-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0010_alter_apply_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchased',
            name='bill_photo',
            field=models.ImageField(upload_to='update'),
        ),
        migrations.AlterField(
            model_name='vendorinfo',
            name='vendor_bill_photo',
            field=models.ImageField(upload_to='update'),
        ),
    ]
