# Generated by Django 5.1.3 on 2024-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0011_alter_itempurchased_bill_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('confrim_password', models.CharField(max_length=255)),
            ],
        ),
    ]
