# Generated by Django 5.1.3 on 2024-12-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0012_technicians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='confrim_password',
        ),
    ]
