# Generated by Django 5.1.3 on 2024-12-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0013_remove_technicians_confrim_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='confrim_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
    ]
