# Generated by Django 5.1.3 on 2024-12-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0015_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
