# Generated by Django 5.1.3 on 2024-12-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0018_alter_apply_service_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='service_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.profile'),
        ),
    ]
