# Generated by Django 5.1.3 on 2024-12-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0025_alter_itempurchased_bill_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcharge',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
        migrations.AlterField(
            model_name='vendorinfo',
            name='vendor_bill_photo',
            field=models.ImageField(upload_to='vendorinfo'),
        ),
    ]
