# Generated by Django 5.1.3 on 2024-12-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0026_fuelcharge_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelcharge',
            name='customer',
        ),
    ]
