# Generated by Django 5.1.3 on 2024-12-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0027_remove_fuelcharge_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatus',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
        migrations.AddField(
            model_name='foodallowance',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
        migrations.AddField(
            model_name='fuelcharge',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
        migrations.AddField(
            model_name='itempurchased',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
        migrations.AddField(
            model_name='vendorinfo',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
    ]
