# Generated by Django 5.1.3 on 2024-12-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0028_currentstatus_customer_foodallowance_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstatus',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='foodallowance',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='fuelcharge',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='itempurchased',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='vendorinfo',
            name='customer',
        ),
    ]
