# Generated by Django 5.1.3 on 2024-12-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0029_remove_currentstatus_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcharge',
            name='apply',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_charges', to='workapp.apply'),
        ),
    ]
