# Generated by Django 5.1.3 on 2024-12-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0031_alter_fuelcharge_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcharge',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.apply'),
        ),
    ]
