# Generated by Django 5.1.3 on 2024-12-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0032_alter_fuelcharge_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelcharge',
            name='apply',
        ),
    ]
