# Generated by Django 5.1.3 on 2024-12-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0034_fuelcharge_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelcharge',
            name='customer',
        ),
    ]
