# Generated by Django 5.1.3 on 2024-12-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0036_fuelcharge_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcharge',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_charges', to='workapp.apply'),
        ),
    ]
