# Generated by Django 5.1.3 on 2024-12-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0037_fuelcharge_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodallowance',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_allowances', to='workapp.apply'),
        ),
    ]
