# Generated by Django 5.1.3 on 2024-12-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0040_vendorinfo_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinfo',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='workapp.apply'),
        ),
    ]
