# Generated by Django 5.1.3 on 2024-12-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0041_alter_vendorinfo_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatus',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_status_entries', to='workapp.apply'),
        ),
    ]
