# Generated by Django 5.1.3 on 2024-12-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0043_fuelcharge_customer_name_fuelcharge_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcharge',
            name='customer_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='fuelcharge',
            name='issue',
            field=models.TextField(),
        ),
    ]
