# Generated by Django 5.1.3 on 2024-12-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0047_itempurchased_customer_name_itempurchased_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchased',
            name='customer_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='itempurchased',
            name='issue',
            field=models.TextField(),
        ),
    ]
