# Generated by Django 5.1.3 on 2024-12-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0049_vendorinfo_customer_name_vendorinfo_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatus',
            name='customer_name',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='issue',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='vendorinfo',
            name='customer_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='vendorinfo',
            name='issue',
            field=models.TextField(),
        ),
    ]
