# Generated by Django 5.1.3 on 2024-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0050_currentstatus_customer_name_currentstatus_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstatus',
            name='customer_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='issue',
            field=models.TextField(),
        ),
    ]
